# Generated by Django 3.2.19 on 2023-05-11 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cping23', '0002_equipo_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablaposiciones',
            name='diferencia_goles',
            field=models.IntegerField(default=0),
        ),
    ]
